### ISSUE TITLE
Some explanation of what this does ?

### ISSUE THREAD

**Issue by Saxin** [iphong/auto-fpv#1]
Hi any chance you can explain the purpose of this repo ?
Thanks in advance.

**Comment by iphong** [comment]
Hey, it was attempt to solve the FPV channel conflict problem. If you are into fpv quad racing, you know what happens when your flying and someone plugs in their quad right? So i thought it would be nice if you can some how quickly switch to another video channel and continue flying. Existing analog video equipment is one way only and nothing you can do about it.

So my idea was to control the vtx using betaflight via transmitter radio module and get synchronized over telemetry on the tx, then control to the vrx module via bluetooth. I actually made a working prototype, but it the entire mod is quite complicated.

Now the new DJI digital fpv system has solved all problems, so I think that was an end to this project.

[Demo working prototype](https://youtu.be/dkdR_Y_Onvs)
